### ISSUE TITLE
entry: clang-format -i

### ISSUE THREAD

**Issue by ghost** [doublify/pre-commit-clang-format#2]
Hey,

About `.pre-commit-hooks.yaml`: shouldn't the `-i` argument be part of the `entry`?
Because without it this whole thing doesn't work.
The docs say this about `entry`:

    entry can also contain arguments that will not be overridden such as entry: autopep8 -i.

I tried to use this repo like this:

```
repos:
  - repo: git://github.com/doublify/pre-commit-clang-format
    rev: master
    hooks:
    - id: clang-format
      args: ['-style=LLVM']
```

This didn't work but it took me a while to realize why.
